import type { AppLocale } from "@/lib/i18n/config";

const copy = {
  "zh-CN": {
    header: {
      loginLabel: "登录",
      accountLabel: "账户",
      accountAriaLabel: "打开账户",
    },
    login: {
      metadataTitle: "邮箱登录",
      metadataDescription: "使用邮箱验证码登录读写札记。",
      eyebrow: "READER ACCESS · 读者通行证",
      title: "用邮箱，继续阅读。",
      description: "无需设置密码。验证码会发送到你的邮箱，首次验证将自动创建读者账号。",
      emailLabel: "邮箱地址",
      emailPlaceholder: "name@example.com",
      displayNameLabel: "显示名称",
      displayNameHint: "首次注册时使用，登录后仍可修改。",
      displayNamePlaceholder: "怎么称呼你",
      sendCodeButton: "发送验证码",
      sendingCodeButton: "正在发送",
      privacyHint: "邮箱仅用于登录和账号关联，不会公开显示。",
      codeTitle: "查收验证码",
      codeDescriptionTemplate: "我们已向 {email} 发送 6 位验证码。",
      codeLabel: "验证码",
      codePlaceholder: "000000",
      verifyButton: "验证并登录",
      verifyingButton: "正在验证",
      changeEmailButton: "更换邮箱",
      resendButton: "重新发送",
      resendCountdownTemplate: "{seconds} 秒后可重发",
      successMessage: "登录成功，正在返回。",
      errors: {
        invalidEmail: "请输入有效的邮箱地址。",
        deliveryUnavailable: "邮件服务暂时不可用，请稍后再试。",
        rateLimitedTemplate: "请求过于频繁，请在 {seconds} 秒后再试。",
        invalidCode: "验证码不正确，请检查后重试。",
        expiredCode: "验证码已过期，请重新发送。",
        tooManyAttempts: "尝试次数过多，请重新发送验证码。",
        disabledUser: "该账号当前无法登录。",
        invalidRequest: "请求无效，请刷新页面后重试。",
      },
    },
    account: {
      metadataTitle: "我的账户",
      eyebrow: "ACCOUNT · 账户",
      title: "我的账户",
      description: "管理公开显示名称和登录邮箱。",
      displayNameLabel: "显示名称",
      emailLabel: "登录邮箱",
      verifiedLabel: "已验证",
      memberSinceLabel: "加入时间",
      saveButton: "保存名称",
      savingButton: "正在保存",
      savedMessage: "显示名称已更新。",
      invalidName: "请输入有效的显示名称。",
      logoutButton: "退出登录",
      adminAction: "后台管理",
    },
    comments: {
      signInTitle: "登录后参与讨论",
      signInDescription: "评论会自动关联你的读者账号，无需重复填写昵称和邮箱。",
      signInButton: "邮箱登录",
      signedInTemplate: "以 {name} 的身份评论",
      accountBadge: "已验证读者",
      bodyLabel: "评论内容",
      submitButton: "提交评论",
      submittingButton: "正在提交",
      loginRequired: "请先登录后再发表评论。",
    },
    adminUsers: {
      title: "用户",
      description: "管理邮箱验证用户、评论关联和登录状态。",
      empty: "还没有注册用户。",
      nameLabel: "用户",
      statusLabel: "状态",
      commentsLabel: "评论",
      lastLoginLabel: "最近登录",
      activeLabel: "正常",
      disabledLabel: "已停用",
      administratorLabel: "管理员",
      disableButton: "停用",
      enableButton: "启用",
      neverLabel: "尚未登录",
    },
  },
  en: {
    header: {
      loginLabel: "Sign in",
      accountLabel: "Account",
      accountAriaLabel: "Open account",
    },
    login: {
      metadataTitle: "Email sign in",
      metadataDescription: "Sign in to Read & Write with an email code.",
      eyebrow: "READER ACCESS",
      title: "Continue with email.",
      description:
        "No password required. We will email you a code; your reader account is created after the first verification.",
      emailLabel: "Email address",
      emailPlaceholder: "name@example.com",
      displayNameLabel: "Display name",
      displayNameHint: "Used for first-time registration and editable later.",
      displayNamePlaceholder: "How should we call you?",
      sendCodeButton: "Send code",
      sendingCodeButton: "Sending",
      privacyHint: "Your email is used for sign-in and is never shown publicly.",
      codeTitle: "Check your inbox",
      codeDescriptionTemplate: "We sent a 6-digit code to {email}.",
      codeLabel: "Verification code",
      codePlaceholder: "000000",
      verifyButton: "Verify and sign in",
      verifyingButton: "Verifying",
      changeEmailButton: "Use another email",
      resendButton: "Resend code",
      resendCountdownTemplate: "Resend in {seconds}s",
      successMessage: "Signed in. Redirecting.",
      errors: {
        invalidEmail: "Enter a valid email address.",
        deliveryUnavailable: "Email delivery is temporarily unavailable.",
        rateLimitedTemplate: "Too many requests. Try again in {seconds} seconds.",
        invalidCode: "That code is not correct.",
        expiredCode: "That code has expired. Request a new one.",
        tooManyAttempts: "Too many attempts. Request a new code.",
        disabledUser: "This account cannot sign in.",
        invalidRequest: "Invalid request. Refresh the page and try again.",
      },
    },
    account: {
      metadataTitle: "My account",
      eyebrow: "ACCOUNT",
      title: "My account",
      description: "Manage your public display name and sign-in email.",
      displayNameLabel: "Display name",
      emailLabel: "Sign-in email",
      verifiedLabel: "Verified",
      memberSinceLabel: "Member since",
      saveButton: "Save name",
      savingButton: "Saving",
      savedMessage: "Display name updated.",
      invalidName: "Enter a valid display name.",
      logoutButton: "Sign out",
      adminAction: "Admin dashboard",
    },
    comments: {
      signInTitle: "Sign in to join the discussion",
      signInDescription:
        "Comments are linked to your verified reader account, so you never need to re-enter a name or email.",
      signInButton: "Sign in with email",
      signedInTemplate: "Commenting as {name}",
      accountBadge: "Verified reader",
      bodyLabel: "Comment",
      submitButton: "Submit comment",
      submittingButton: "Submitting",
      loginRequired: "Sign in before posting a comment.",
    },
    adminUsers: {
      title: "Users",
      description: "Manage verified users, comment links, and sign-in access.",
      empty: "No registered users yet.",
      nameLabel: "User",
      statusLabel: "Status",
      commentsLabel: "Comments",
      lastLoginLabel: "Last sign in",
      activeLabel: "Active",
      disabledLabel: "Disabled",
      administratorLabel: "Administrator",
      disableButton: "Disable",
      enableButton: "Enable",
      neverLabel: "Never",
    },
  },
} as const;

export function getAccountCopy(locale: AppLocale) {
  return copy[locale];
}
