import type { AppLocale } from "@/lib/i18n/config";

const dailyCopy = {
  "zh-CN": {
    navLabel: "日常",
    public: {
      metadataTitle: "日常",
      metadataDescription: "一些没有写成长文，却仍然值得留下的生活片段。",
      eyebrow: "MOMENTS · 日常",
      title: "一些没写成长文的时刻。",
      description: "随手记下途中所见、当下所想，以及生活里不必展开成一篇文章的小事。",
      profileName: "读写札记",
      profileHandle: "@daily",
      pinnedLabel: "置顶日常",
      locationLabel: "地点",
      viewDetailLabel: "打开这条日常",
      shareLabel: "分享",
      shareSuccessLabel: "链接已复制",
      imageCountTemplate: "{count} 张图片",
      allLabel: "全部",
      archiveHeading: "时间索引",
      topicsHeading: "最近话题",
      statsHeading: "日常一览",
      totalLabel: "条记录",
      yearsLabel: "个年份",
      filteredTemplate: "当前显示 {count} 条",
      clearFilterLabel: "清除筛选",
      emptyTitle: "这里还很安静",
      emptyDescription: "第一条日常发布后，会从这里开始按时间生长。",
      filteredEmptyTitle: "没有找到相关日常",
      filteredEmptyDescription: "换一个话题或年份继续看看。",
      previousPageLabel: "上一页",
      nextPageLabel: "下一页",
      pageTemplate: "{current} / {total}",
      backLabel: "返回日常",
      notFoundTitle: "这条日常不存在",
      notFoundDescription: "它可能仍是草稿，或已经被移除。",
      previousEntryLabel: "较早一条",
      nextEntryLabel: "较新一条",
      closeGalleryLabel: "关闭图片",
      previousImageLabel: "上一张图片",
      nextImageLabel: "下一张图片",
      imagePositionTemplate: "第 {current} 张，共 {total} 张",
    },
    admin: {
      title: "日常管理",
      description: "快速发布短内容、生活照片与当下片段。",
      composerTitle: "记下此刻",
      composerDescription: "保持简短，也允许它只是一个瞬间。",
      contentLabel: "内容",
      contentPlaceholder: "此刻发生了什么？",
      contentCountTemplate: "{current} / {max}",
      locationLabel: "地点",
      locationPlaceholder: "可选，例如：杭州 · 西湖边",
      occurredAtLabel: "发生时间",
      imagesLabel: "图片",
      imagesDescription: "最多 4 张，每张不超过 4 MB；支持 JPEG、PNG、WebP、GIF。",
      chooseImagesLabel: "选择图片",
      clearImagesLabel: "清空已选",
      removeExistingImageLabel: "移除这张图片",
      statusLabel: "发布状态",
      draftLabel: "草稿",
      publishedLabel: "公开",
      pinnedLabel: "置顶在时间线顶部",
      createButton: "发布日常",
      saveDraftButton: "保存草稿",
      saveButton: "保存修改",
      savingLabel: "正在保存",
      listHeading: "全部日常",
      listDescription: "管理发布状态、置顶顺序和已有内容。",
      emptyTitle: "还没有日常",
      emptyDescription: "上方写下的第一条内容会出现在这里。",
      editLabel: "编辑",
      deleteLabel: "删除",
      deleteConfirmTemplate: "确定删除这条日常吗？关联图片也会一并移除。",
      publishLabel: "发布",
      unpublishLabel: "转为草稿",
      pinLabel: "置顶",
      unpinLabel: "取消置顶",
      backLabel: "返回日常管理",
      editTitle: "编辑日常",
      editDescription: "调整文字、图片、时间或发布状态。",
      imageAltTemplate: "日常图片 {index}",
      messages: {
        contentRequired: "请写下一点内容。",
        contentTooLong: "内容不能超过 1000 个字符。",
        invalidDate: "请选择有效的发生时间。",
        tooManyImages: "一条日常最多包含 4 张图片。",
        invalidImages: "图片上传失败，请确认格式和大小后重试。",
        notFound: "没有找到这条日常。",
        createSuccess: "日常已保存。",
        updateSuccess: "日常已更新。",
        saveFailed: "保存失败，请稍后重试。",
      },
    },
  },
  en: {
    navLabel: "Daily",
    public: {
      metadataTitle: "Daily",
      metadataDescription: "Small moments that never became essays, but were still worth keeping.",
      eyebrow: "MOMENTS · DAILY",
      title: "Moments that did not need an essay.",
      description:
        "Things seen along the way, passing thoughts, and the small parts of life worth keeping.",
      profileName: "Read / Write Notes",
      profileHandle: "@daily",
      pinnedLabel: "Pinned moment",
      locationLabel: "Location",
      viewDetailLabel: "Open this moment",
      shareLabel: "Share",
      shareSuccessLabel: "Link copied",
      imageCountTemplate: "{count} images",
      allLabel: "All",
      archiveHeading: "Archive",
      topicsHeading: "Recent topics",
      statsHeading: "At a glance",
      totalLabel: "moments",
      yearsLabel: "years",
      filteredTemplate: "Showing {count}",
      clearFilterLabel: "Clear filter",
      emptyTitle: "It is quiet here",
      emptyDescription: "The timeline will begin growing after the first moment is published.",
      filteredEmptyTitle: "No matching moments",
      filteredEmptyDescription: "Try another topic or year.",
      previousPageLabel: "Previous",
      nextPageLabel: "Next",
      pageTemplate: "{current} / {total}",
      backLabel: "Back to Daily",
      notFoundTitle: "This moment is unavailable",
      notFoundDescription: "It may still be a draft or it may have been removed.",
      previousEntryLabel: "Earlier",
      nextEntryLabel: "Newer",
      closeGalleryLabel: "Close images",
      previousImageLabel: "Previous image",
      nextImageLabel: "Next image",
      imagePositionTemplate: "Image {current} of {total}",
    },
    admin: {
      title: "Daily",
      description: "Publish short notes, everyday photos, and passing moments.",
      composerTitle: "Capture this moment",
      composerDescription: "Keep it brief, or let it be nothing more than a moment.",
      contentLabel: "Content",
      contentPlaceholder: "What is happening?",
      contentCountTemplate: "{current} / {max}",
      locationLabel: "Location",
      locationPlaceholder: "Optional, e.g. Hangzhou · West Lake",
      occurredAtLabel: "When",
      imagesLabel: "Images",
      imagesDescription: "Up to 4 images, 4 MB each. JPEG, PNG, WebP, or GIF.",
      chooseImagesLabel: "Choose images",
      clearImagesLabel: "Clear selection",
      removeExistingImageLabel: "Remove this image",
      statusLabel: "Status",
      draftLabel: "Draft",
      publishedLabel: "Public",
      pinnedLabel: "Pin to the top of the timeline",
      createButton: "Publish moment",
      saveDraftButton: "Save draft",
      saveButton: "Save changes",
      savingLabel: "Saving",
      listHeading: "All moments",
      listDescription: "Manage publication status, pinned order, and existing content.",
      emptyTitle: "No moments yet",
      emptyDescription: "Your first entry from the composer above will appear here.",
      editLabel: "Edit",
      deleteLabel: "Delete",
      deleteConfirmTemplate: "Delete this moment? Its uploaded images will also be removed.",
      publishLabel: "Publish",
      unpublishLabel: "Move to draft",
      pinLabel: "Pin",
      unpinLabel: "Unpin",
      backLabel: "Back to Daily admin",
      editTitle: "Edit moment",
      editDescription: "Adjust the text, images, time, or publication status.",
      imageAltTemplate: "Daily image {index}",
      messages: {
        contentRequired: "Write something before saving.",
        contentTooLong: "Content must be 1,000 characters or fewer.",
        invalidDate: "Choose a valid date and time.",
        tooManyImages: "A moment can contain up to 4 images.",
        invalidImages: "The upload failed. Check the image format and size.",
        notFound: "This moment could not be found.",
        createSuccess: "Moment saved.",
        updateSuccess: "Moment updated.",
        saveFailed: "Unable to save. Please try again.",
      },
    },
  },
} as const;

export type DailyCopy = (typeof dailyCopy)[AppLocale];

export function getDailyCopy(locale: AppLocale) {
  return dailyCopy[locale];
}
