import type { AppLocale } from "@/lib/i18n/config";

export const privateNotesCopy = {
  "zh-CN": {
    sidebarLabel: "私笺",
    eyebrow: "只属于你的工作台",
    title: "私笺",
    description: "把还不想公开的想法、方向和下一步，放在一个安静且可持续回看的地方。",
    privacyLabel: "仅管理员可见",
    privacyDescription: "不进入前台导航、搜索、RSS 或站点地图。",
    captureTitle: "写下此刻",
    captureDescription: "先留下，再慢慢整理。内容会保存在服务器本地数据库中。",
    createButton: "保存记录",
    savingLabel: "保存中…",
    updateButton: "保存修改",
    backButton: "返回私笺",
    editButton: "编辑",
    completeButton: "标记完成",
    reopenButton: "重新打开",
    archiveButton: "归档",
    deleteButton: "删除",
    deleteConfirm: "确定删除这条私笺吗？此操作无法撤销。",
    titleLabel: "标题",
    titlePlaceholder: "给这段想法一个可以回来的名字",
    contentLabel: "内容",
    contentPlaceholder: "写下你正在思考的事、想验证的方向，或下一步行动…",
    kindLabel: "记录类型",
    thoughtLabel: "思绪",
    goalLabel: "目标计划",
    priorityLabel: "优先级",
    priority: { low: "低", medium: "中", high: "高" },
    targetDateLabel: "目标日期",
    noTargetDate: "暂不设定",
    tagsLabel: "标签",
    tagsPlaceholder: "用逗号分隔，例如：写作、产品、长期",
    tabs: { all: "全部", thought: "思绪", goal: "目标", completed: "已完成" },
    searchPlaceholder: "搜索私笺…",
    emptyTitle: "这里还很安静",
    emptyDescription: "从一条不必完美的记录开始，给未来的自己留一个入口。",
    noResultsTitle: "没有匹配的记录",
    noResultsDescription: "换一个关键词，或清除当前筛选。",
    stats: {
      all: "全部记录",
      activeGoals: "进行中的目标",
      openThoughts: "未整理思绪",
      completed: "已经完成",
    },
    updatedTemplate: "更新于 {date}",
    targetTemplate: "截止 {date}",
    progressLabel: "进度",
    status: { active: "进行中", completed: "已完成", archived: "已归档" },
    messages: {
      createSuccess: "已保存到私笺。",
      updateSuccess: "修改已保存。",
      deleteSuccess: "记录已删除。",
      completeSuccess: "目标已完成。",
      reopenSuccess: "目标已重新打开。",
      archiveSuccess: "记录已归档。",
      invalid: "请填写标题和内容。",
      failed: "保存失败，请稍后重试。",
    },
  },
  en: {
    sidebarLabel: "Private",
    eyebrow: "A workspace for your eyes only",
    title: "Private notes",
    description: "Keep the thoughts, directions, and next steps that are not ready to share in one quiet place.",
    privacyLabel: "Admin only",
    privacyDescription: "Excluded from public navigation, search, RSS, and the sitemap.",
    captureTitle: "Capture the moment",
    captureDescription: "Leave it rough now; shape it later. Everything stays in the local server database.",
    createButton: "Save note",
    savingLabel: "Saving…",
    updateButton: "Save changes",
    backButton: "Back to private notes",
    editButton: "Edit",
    completeButton: "Mark complete",
    reopenButton: "Reopen",
    archiveButton: "Archive",
    deleteButton: "Delete",
    deleteConfirm: "Delete this private note? This cannot be undone.",
    titleLabel: "Title",
    titlePlaceholder: "Give this thought a name you can return to",
    contentLabel: "Content",
    contentPlaceholder: "Write what you are thinking, a direction to test, or the next action…",
    kindLabel: "Record type",
    thoughtLabel: "Thought",
    goalLabel: "Goal / plan",
    priorityLabel: "Priority",
    priority: { low: "Low", medium: "Medium", high: "High" },
    targetDateLabel: "Target date",
    noTargetDate: "No date yet",
    tagsLabel: "Tags",
    tagsPlaceholder: "Comma-separated, e.g. writing, product, long-term",
    tabs: { all: "All", thought: "Thoughts", goal: "Goals", completed: "Completed" },
    searchPlaceholder: "Search private notes…",
    emptyTitle: "It is quiet here",
    emptyDescription: "Start with one imperfect note and leave a doorway for your future self.",
    noResultsTitle: "No matching notes",
    noResultsDescription: "Try another keyword or clear the current filter.",
    stats: {
      all: "All records",
      activeGoals: "Active goals",
      openThoughts: "Unsorted thoughts",
      completed: "Completed",
    },
    updatedTemplate: "Updated {date}",
    targetTemplate: "Due {date}",
    progressLabel: "Progress",
    status: { active: "Active", completed: "Completed", archived: "Archived" },
    messages: {
      createSuccess: "Saved to private notes.",
      updateSuccess: "Changes saved.",
      deleteSuccess: "Note deleted.",
      completeSuccess: "Goal completed.",
      reopenSuccess: "Goal reopened.",
      archiveSuccess: "Note archived.",
      invalid: "Add a title and some content.",
      failed: "Could not save. Try again.",
    },
  },
} as const;

export function getPrivateNotesCopy(locale: AppLocale) {
  return privateNotesCopy[locale];
}
